FROM apache/flink:1.19.2

# Set working dir
WORKDIR /opt/flink

# Copy config
COPY ./flink-conf/ conf/

# Put the workers in conf/workers
RUN echo -e "kafka-docker_flink-taskmanager_1\nkafka-docker_flink-taskmanager_2" > /opt/flink/conf/workers

# Create the jobs directory
RUN mkdir -p /opt/flink/jobs

# Download connector JARs
WORKDIR /opt/flink/lib/

RUN curl -fSL https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.3.0-1.19/flink-sql-connector-kafka-3.3.0-1.19.jar -o flink-sql-connector-kafka-3.3.0-1.19.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/apache/flink/flink-avro-confluent-registry/1.19.2/flink-avro-confluent-registry-1.19.2.jar -o flink-avro-confluent-registry-1.19.2.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.19/flink-connector-jdbc-3.2.0-1.19.jar -o flink-connector-jdbc-3.2.0-1.19.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/apache/avro/avro/1.12.0/avro-1.12.0.jar -o avro-1.12.0.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/apache/flink/flink-avro/1.19.2/flink-avro-1.19.2.jar -o flink-avro-1.19.2.jar && \
    curl -fSL https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.5/jackson-databind-2.13.5.jar -o jackson-databind-2.13.5.jar && \
    curl -fSL https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.5/jackson-core-2.13.5.jar -o jackson-core-2.13.5.jar && \
    curl -fSL https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.5/jackson-annotations-2.13.5.jar -o jackson-annotations-2.13.5.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.5/postgresql-42.7.5.jar -o postgresql-42.7.5.jar && \
    curl -fSL https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.5.1/kafka-schema-registry-client-7.5.1.jar -o kafka-schema-registry-client-7.5.1.jar && \
    curl -fSL https://packages.confluent.io/maven/io/confluent/common-config/7.5.1/common-config-7.5.1.jar -o common-config-7.5.1.jar && \
    curl -fSL https://packages.confluent.io/maven/io/confluent/common-utils/7.5.1/common-utils-7.5.1.jar -o common-utils-7.5.1.jar && \
    curl -fSL https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.9.0/kafka-avro-serializer-7.9.0.jar -o kafka-avro-serializer-7.9.0.jar && \
    curl -fSL https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar -o kafka-clients-3.5.1.jar && \
    curl -fSL https://repo1.maven.org/maven2/com/google/guava/guava/33.4.5-jre/guava-33.4.5-jre.jar -o guava-33.4.5-jre.jar

# Optional: Add SQL job script and custom entrypoint
COPY jobs/ /opt/flink/jobs/
COPY entrypoint.sh /opt/flink/entrypoint.sh
RUN chmod +x /opt/flink/entrypoint.sh
RUN apt-get update && apt-get install -y netcat

# Use custom entrypoint
ENTRYPOINT ["/opt/flink/entrypoint.sh"]